In [113]:
# import libraries
import os
import numpy as np 
import pandas as pd 
from scipy.signal import resample 
import matplotlib.pyplot as plt 

In [114]:
#set the working directory
os.chdir('/Users/rossbrancati/Desktop/PFP_Project/EMG/')
data_directory = os.path.join(os.getcwd(), 'Data')
directory = sorted(os.listdir(data_directory))
directory.remove('.DS_Store')

#make a new directory to store the PCA matrices in
pca_directory = os.path.join(os.getcwd(),'PCA_matrices')

In [122]:
#Create an empty matrix for each muscle that will be appended with each new sheet. This is 1 column of 101 zeros
biceps_femoris = np.zeros([101,1])
glute_max = np.zeros([101,1])
glute_med = np.zeros([101,1])
lateral_gastroc = np.zeros([101,1])
medial_gastroc = np.zeros([101,1])
rectus_femoris = np.zeros([101,1])
soleus = np.zeros([101,1])
semitendinosus = np.zeros([101,1])
tibialis_anterior = np.zeros([101,1])
vastus_lateralis = np.zeros([101,1])
vastus_medialis = np.zeros([101,1])

#Create a list that contains each of the empty matrices for looping over to store data
pca_file_list = [biceps_femoris, glute_max, glute_med, lateral_gastroc, medial_gastroc, rectus_femoris, 
                 soleus, semitendinosus, tibialis_anterior, vastus_lateralis, vastus_medialis]

#create a list of strings for exporting files
pca_file_list_names = ['biceps_femoris', 'glute_max', 'glute_med', 'lateral_gastroc', 'medial_gastroc', 'rectus_femoris', 
                 'soleus', 'semitendinosus', 'tibialis_anterior', 'vastus_lateralis', 'vastus_medialis']

In [123]:
#Loop through each file 
total_strides = 0

for file_idx,file_name in enumerate(directory):
    
    #set variable as file path
    file_path = os.path.join(data_directory,file_name)
    
    #load the file
    raw_file = pd.read_csv(file_path,sep='\t',skiprows=4)
    _,num_cols = raw_file.shape
    
    #preallocate a matrix to store the resampled data in
    resampled_matrix = np.zeros([101,num_cols-1])
    
    #loop through each column in the raw_file and resample to 101 data points
    #list of the varaibles which represent each column
    column_list=raw_file.columns
    
    #loop through each column
    for col_idx,column_id in enumerate(column_list[1:]):
        
        #get the current column as a vector
        current_col = np.array(raw_file.loc[:,column_id].dropna())
        
        #resample to 101 data points
        resamp_col = resample(current_col,101)
        
        #store resamples vector in resampled matrix
        resampled_matrix[:,col_idx] = resamp_col
        
        
    #stride counter - used for plotting purposes
    stride_count = int((num_cols-1)/11)
    #print(stride_count)
    
    #count the total number of strides
    total_strides = total_strides + stride_count
    print(total_strides)
    
    #append muscle matrices with data from new sheet
    #biceps_femoris = np.hstack((biceps_femoris,resampled_matrix[:,0:stride_count]))
    #glute_max = np.hstack((glute_max,resampled_matrix[:,stride_count:stride_count*2]))
    #glute_med = np.hstack((glute_med,resampled_matrix[:,stride_count*2:stride_count*3]))
    #lateral_gastroc = np.hstack((lateral_gastroc,resampled_matrix[:,stride_count*3:stride_count*4]))
    #medial_gastroc = np.hstack((medial_gastroc,resampled_matrix[:,stride_count*4:stride_count*5]))
    #rectus_femoris = np.hstack((rectus_femoris,resampled_matrix[:,stride_count*5:stride_count*6]))
    #soleus = np.hstack((soleus,resampled_matrix[:,stride_count*6:stride_count*7]))
    #semitendinosus = np.hstack((semitendinosus,resampled_matrix[:,stride_count*7:stride_count*8]))
    #tibialis_anterior = np.hstack((tibialis_anterior,resampled_matrix[:,stride_count*8:stride_count*9]))
    #vastus_lateralis = np.hstack((vastus_lateralis,resampled_matrix[:,stride_count*9:stride_count*10]))
    #vastus_medialis = np.hstack((vastus_medialis,resampled_matrix[:,stride_count*10:stride_count*11]))
    
    for i in range(11):
        pca_file_list[i] = np.hstack((pca_file_list[i],resampled_matrix[:,i*stride_count:(i+1)*stride_count]))

12
23
35
49
62
74
86
99
111
124
136
149
163
176
188
200
212
224
237
251
266
278
291
304
317
330
343
356
369
382
394
406
420
434
447
460
473
486
499
512
526
539
552
564
577
589
602
615
628
641
654
666
678
690
702
715
728
740
752
764
775
786
799
813
825
837
849
861
873
886
899
912
925
938
951
963
975
988
1000
1012
1025
1039
1051
1063
1074
1085
1098
1111
1124
1137
1150
1162
1174
1187
1200
1213
1227
1241
1253
1265
1276
1287
1298
1309
1323
1337


In [ ]:
#normalize data to the max value for each particular stride

#loop through each EMG datasheet
for muscle in range(11):
    
    _,cols = pca_file_list[muscle].shape
    current_file = pca_file_list[muscle[:,1:]]
    
    current_norm_file = pca_file_list_norm[muscle]
    
    #loop through each column of the particular muscles data
    for n in range(cols):
        
        #grab the maximum value of the particular column
        max_EMG = max(current_file[:,n])
        
        #divide each component of the column by the max value
        normalized_vector = np.divide(current_file[:,n], max_EMG)
        
        #store the current vector in new matrix that contains normalized values
        current_norm_file[:,n] = normalized_vector
        
    #transpose the matrix 
    
    

In [10]:
#remove first column of zeros from each of the muscle matrices and export file to csv
for ii in range(11):
    pca_file_list[ii] = pca_file_list[ii][:,1:]
    current_file_id = os.path.join('/Users/rossbrancati/Desktop/PFP_Project/EMG/PCA_matrices',pca_file_list_names[ii])
    np.savetxt(current_file_id+'.txt', pca_file_list[ii], delimiter="\t")

In [118]:
muscle = 0
current_file = pca_file_list[muscle][:,1:]
_,cols = pca_file_list[muscle].shape
print(current_file)
current_norm_file = pca_file_list_norm[muscle]
current_file.shape

[[0.01283016 0.01302616 0.01620639 ... 0.02632801 0.02427739 0.02757002]
 [0.0106486  0.01316343 0.01227453 ... 0.02106483 0.02713451 0.01801699]
 [0.01090128 0.01237654 0.01161806 ... 0.02049531 0.02128994 0.01781569]
 ...
 [0.01763349 0.02390698 0.01607368 ... 0.03544403 0.03282003 0.04533475]
 [0.01536527 0.01175964 0.01792289 ... 0.03305468 0.02967183 0.04408175]
 [0.01506553 0.01450652 0.01694345 ... 0.03344133 0.02385878 0.04240834]]


(101, 1337)

In [124]:
for n in range(cols-1):
        
        #grab the maximum value of the particular column
        max_EMG = max(current_file[:,n])
        
        #divide each component of the column by the max value
        normalized_vector = np.divide(current_file[:,n], max_EMG)
        
        #change the dimensions of current_norm_file from (101,1) to (100,) so that the dimensions
        #agree with normalized_vector
        current_norm_file = np.squeeze(current_norm_file)
        
        #store the current vector in new matrix that contains normalized values
        current_norm_file = np.append([current_norm_file], [normalized_vector])

/Users/rossbrancati/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys


In [125]:
print(current_norm_file)
current_norm_file.shape

[0.         0.         0.         ... 0.89463658 0.86990982 0.83688684]


(270175,)

In [97]:
normalized_vector = np.divide(current_file[:,n], max_EMG)
normalized_vector.shape
type(normalized_vector)

numpy.ndarray

In [101]:
np.reshape(normalized_vector, 101)

array([0.10408987, 0.08639108, 0.08844109, 0.08354995, 0.08865956,
       0.08292458, 0.09866122, 0.08162183, 0.22512071, 0.56728554,
       0.58640442, 0.59453201, 0.58831967, 0.60019905, 0.5918485 ,
       0.60265208, 0.59369508, 0.6197239 , 0.61093952, 0.62739797,
       0.61460195, 0.63712912, 0.42082616, 0.21224367, 0.22842833,
       0.20493496, 0.20383752, 0.1941231 , 0.19361864, 0.19164199,
       0.15948748, 0.10443794, 0.11337257, 0.04566011, 0.03754398,
       0.03253028, 0.032471  , 0.02758384, 0.03235322, 0.02843146,
       0.03041453, 0.02526342, 0.02663837, 0.02361862, 0.02674781,
       0.02292489, 0.02809076, 0.02683722, 0.03051605, 0.02658382,
       0.03072393, 0.03355081, 0.04018407, 0.03586939, 0.03991702,
       0.0368768 , 0.04174996, 0.04002086, 0.0450196 , 0.04024111,
       0.04335881, 0.03768712, 0.0421937 , 0.03737124, 0.03940435,
       0.02603823, 0.03070355, 0.0234987 , 0.03094782, 0.02066393,
       0.02810813, 0.02694766, 0.08914847, 0.09593392, 0.52133

In [102]:
normalized_vector.shape

(101,)

In [107]:
a = np.squeeze(current_norm_file)

In [108]:
a.shape

(101,)